### ISSUE TITLE
Не информативно

### ISSUE THREAD

**Issue by KomarDL** [kostyaTsy/OSiSP#3]
https://github.com/kostyaTsy/OSiSP/blob/a303d505249fef1dfa3a9acbfb38c6b5d9ebb3e3/lab1/ex6.sh#L11
https://github.com/kostyaTsy/OSiSP/blob/a303d505249fef1dfa3a9acbfb38c6b5d9ebb3e3/lab1/ex6.sh#L17

Сообщения не помогают решить проблему

**Comment by kostyaTsy** [comment]
Fixed
